### ISSUE TITLE
Numpy build fails

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/cogeo-mosaic#10]
The numpy `--no-binary` flag causes the following error when building the Docker image:

`ERROR: Service 'base' failed to build: The command '/bin/sh -c pip3 install . --no-binary numpy,rasterio -t $PACKAGE_PREFIX -U' returned a non-zero code: 1`

The error occurs when compiling numpy with `gcc`:

`
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-x86_64-3.6/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/var/lang/include/python3.6m -Ibuild/src.linux-x86_64-3.6/numpy/core/src/common -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/common -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -c build/src.linux-x86_64-3.6/numpy/core/src/npysort/radixsort.c -o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/numpy/core/src/npysort/radixsort.o -MMD -MF build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/numpy/core/src/npysort/radixsort.o.d" failed with exit status 1
`

Removing the `--no-binary` flag for numpy fixes this error (see [here](https://github.com/geospatial-jeff/cogeo-mosaic/commit/9f1575565e2f59cad5f605728d7f96b20e790767)).  This fix is based off of [Seth's rasterio lambda layer](https://github.com/mojodna/lambda-layer-rasterio/blame/master/Dockerfile#L123-L124).

**Comment by vincentsarago** [comment]
I've seen this recently I had to force `numpy==0.16` to build it.

**Comment by vincentsarago** [comment]
I've added a temporary fix here https://github.com/developmentseed/cogeo-mosaic/blob/master/Dockerfile#L13
