### ISSUE TITLE
Multiple mosaics within a single DynamoDB table

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#116]
AWS has a limit of 256 DynamoDB tables per region per account. Since DynamoDB is the most efficient mosaic storage type for very large mosaics, it would be nice to be able to store multiple mosaics in a single table.

According to @geospatial-jeff and [this AWS blog post](https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/), mosaic keys of the sort `${mosaic-name}-${quadkey}` would maintain efficient queries.

Along the same lines: how to store top-level mosaicjson metadata. Currently the metadata for a table is stored as quadkey `-1`. It would be straightforward to keep metadata files as `${mosaic-name}--1` (an extra `-` for `-1`).

Another good question is how to keep track of all the mosaics in a single table. I'm guessing that listing all the keys that are like `.*-1` is inefficent. Would it be worthwhile to have another file that lists the key names within the table?

The parameter could be named something like `table_subname`, and default to `None` for backwards compatibility.

@geospatial-jeff

**Comment by vincentsarago** [comment]
👍 sounds good to me!

Also, even with this new way to store the mosaics, the limit of 256 would still be a shame (think about mosaic as a service where each table is a user 🤷‍♂️. I wonder what other DB would be good for storing mosaic: elastricsearch ?

**Comment by kylebarron** [comment]
Well you could effectively never use more than one dynamodb table... you'd store every mosaic as a "subkey" within a single dynamodb table, so you have 255 tables for everything else

**Comment by geospatial-jeff** [comment]
And if you wanted to support users you could have a user table with unique ids for each user and include the user's id in the primary key of the mosaic table.
