### ISSUE TITLE
Do not return the list of quadkey by default

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic#126]
https://github.com/developmentseed/cogeo-mosaic/blob/4946b9cb33290d1d90fcce7fdfffed6f69177936/cogeo_mosaic/backends/base.py#L77

This works well on small mosaic, but if you have 10000 quakdey (first mosaicjson file will be quite big) it won't be really efficient.

**Comment by kylebarron** [comment]
For all backends?

**Comment by vincentsarago** [comment]
@kylebarron yes, basically we should add an options like we do in dynamoDB https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/backends/dynamodb.py#L56
