### ISSUE TITLE
add git+ to the pip install url

### ISSUE THREAD

**Issue by stvno** [developmentseed/cogeo-mosaic#13]
I'm trying to install cogeo-mosaic on ubuntu 19.04 using the provided command:
`pip install --user http://github.com/developmentseed/cogeo-mosaic` but it fails with
```
$ pip install --user http://github.com/developmentseed/cogeo-mosaic
Collecting http://github.com/developmentseed/cogeo-mosaic
  Cache entry deserialization failed, entry ignored
  Downloading http://github.com/developmentseed/cogeo-mosaic
     \ 143kB 550kB/s
  Cannot unpack file /tmp/pip-unpack-ld1calx8/cogeo-mosaic (downloaded from /tmp/pip-req-build-jxhejr6o, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-jxhejr6o
```

A quick google suggested prepending the url with git+ https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by vincentsarago** [comment]
thanks for the issue @stvno, I'll fix this ;-)

**Comment by stvno** [comment]
related: it still fails on ubuntu 19.04 with python 3.7.3 on trying to install vtzero. A bit more digging gave me `pip install --user cython==0.28` to solve the vtzero problem. Maybe a useful hint for people using pip?

**Comment by vincentsarago** [comment]
yeah this is a vtzero problem, but I'll add it in the readme 👌
