### ISSUE TITLE
CI might be different for a PR than for push

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#135]
This CI failed for me on my fork:
https://github.com/kylebarron/cogeo-mosaic/runs/1295349087?check_suite_focus=true

but this CI on the corresponding PR passed:
https://github.com/developmentseed/cogeo-mosaic/runs/1295353448

you can see from the commit hashes that these are the same commit

**Comment by vincentsarago** [comment]
@kylebarron I think you fixed this!
