### ISSUE TITLE
In-memory mosaic backend

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#152]
If you have a mosaic in memory and you want to access backend methods like `.tile`, you currently need to know that you can pass `FileBackend(path=None, mosaic_def=...)`. It might be clearer to expose a `InMemoryBackend` that doesn't require a `path` argument.

**Comment by vincentsarago** [comment]
Well i though we solved this with cogeo_mosaic.backends.MosaicBackends, but making an official one would be nice.

If we had a InMemoryBackend (fallback for MosaicBackend when path is not given) we could then make path a required arguments in the other backends 🤷‍♂

**Comment by kylebarron** [comment]
Well I think I'd suggest

```py
def MosaicBackend(url: str = '', *args: Any, **kwargs: Any) -> BaseBackend:
    """Select mosaic backend for url."""
    parsed = urlparse(url)

	...
	
    # file:///{path}
    elif parsed.scheme == "file":
        return FileBackend(parsed.path, *args, **kwargs)

    # Invalid Scheme
    elif parsed.scheme:
        raise ValueError(f"'{parsed.scheme}' is not supported")

	elif url:
        return FileBackend(url, *args, **kwargs)

    # fallback to MemoryBackend
    else:
        return MemoryBackend(*args, **kwargs)
```

Then yes all other backends could have path be required.
