### ISSUE TITLE
update mosaicJSON.bounds type to `tuple(float, float, float, float)`

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic#158]
The only way to enforce a list to be a 4 element object is by using Tuple and that's why we define `bounds` in rio-tiler as 
`tuple(float, float, float, float)` (e.g. https://github.com/cogeotiff/rio-tiler/blob/a10a8c5be8b067dd3ecc72e76bfd740a2b3213c9/rio_tiler/io/base.py#L37)

In the mosaic model we are a bit too permissive with `List[float]`

https://github.com/developmentseed/cogeo-mosaic/blob/7d01981e76cafcb9e58f96b45ee31c9d0ae6878e/cogeo_mosaic/mosaic.py#L69

Changing to `Tuple[Float, Float, Float, Float]` won't change how the object is stored on the json document 

```python
json.dumps((1,1,1,1))
'[1, 1, 1, 1]'
```

**Comment by kylebarron** [comment]
Unless you want three-dimensional bounds with a 6-element iterable 😉
