### ISSUE TITLE
from_features and from_urls error in development

### ISSUE THREAD

**Issue by gllewellyn19** [developmentseed/cogeo-mosaic#180]
Steps to reproduce: In a terminal in MAAP ops or Pilot ops, git clone https://github.com/MAAP-Project/maap-jupyter-ide and follow the steps on the top level readme and the ipycmc readme. Then git clone https://github.com/MAAP-Project/maap-pyand run the commands in that readme. Then launch a notebook with the conda environment that you just created and try to run MosaicJSON.from_urls or MosaicJSON.from_features.
Error: Attached Image 
![image](https://user-images.githubusercontent.com/42745872/124192157-ad666900-da79-11eb-9428-4976b09e11dc.png)
How I fixed the error: I fixed the bug for from_features and from_urls by going into _termui_impl.pyand changing line 83 from  if file is None: to if file is None or isinstance(file, str):. This fixed my error, but I do not know if this may cause errors for other users. This error was occurring for me because the file object in the init function was not None, but "/dev/null" (a string) so it was not caught in that previous if statement and set to default_text_stdout()

**Comment by vincentsarago** [comment]
@gllewellyn19 I think this is now fixed in the latest version (3.0.1) https://github.com/developmentseed/cogeo-mosaic/pull/178
