### ISSUE TITLE
Add `coord_crs` options in point method

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic#209]
https://github.com/developmentseed/cogeo-mosaic/blob/b9b12ae4a4e8affbaf9376feac8d6340820f65f6/cogeo_mosaic/backends/base.py#L233-L241

lon,lat is assumed to be in TMS geographic CRS so we need to convert the coordinates between the `coord_crs` and the tms geographic crs.

The main issue is that TMS (morecantile) uses Pyproj CRS while cogeo-mosaic uses Rasterio CRS. 

In order to convert the lon/lat from coord_crs to TMS's geographic CRS we have to use something like https://github.com/developmentseed/morecantile/blob/main/morecantile/models.py#L199-L209 

ref https://github.com/developmentseed/titiler/issues/631

**Comment by AndrewAnnex** [comment]
@vincentsarago I think the rasterio_crs parameter is available from the basebackend attribute tms.

**Comment by vincentsarago** [comment]
@AndrewAnnex it's available for the TMS crs not the geographic crs
