### ISSUE TITLE
WMTS with Float32 cogeos

### ISSUE THREAD

**Issue by mccarthyryanc** [developmentseed/cogeo-mosaic#22]
I'm getting some errors when testing out the WMTS endpoint:
```
127.0.0.1 - - [15/Nov/2019 10:03:18] "GET /tiles/15/8853/13515@1x.png?url=http%3A%2F%2Flocalhost%3A8787%2Ftest-mosaic.json.gz HTTP/1.1" 204 -
[cogeo-mosaic-tiles] - [ERROR] - PNG driver doesn't support data type Float32. Only eight bit (Byte) and sixteen bit (UInt16) bands supported.
```
My cloud optimized geotiffs are Float32, in order to use the WMTS endpoint do they need to be Byte/UInt16?

Added WMTS url in QGIS as:
```
http://localhost:8080/tiles/wmts?url=http://localhost:8787/test-mosaic.json.gz
```

Where everything is running locally:
```bash
# cogeo server
cogeo-mosaic run --port 8080
# generic server for mosaic file
python -m http.server 8787
```

**Comment by vincentsarago** [comment]
@mccarthyryanc you need rescale your data to a valid Byte range (you can pass `rescale=0,1000` to the request) because for now the tiler can only return webp/jpeg/png which only support Byte data. 

Note: I'm going to push some change to make it possible to get GeoTIFF latest this week.

**Comment by vincentsarago** [comment]
note: I think you should be able to do `http://localhost:8080/tiles/wmts?url=/local/path/to/test-mosaic.json.gz` you don't need fire 2 servers

**Comment by mccarthyryanc** [comment]
@vincentsarago , you are my hero! Rescaling is exactly what I needed!

**Comment by vincentsarago** [comment]
you can check `http://localhost:8080/tiles/docs` or https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/handlers/tiles.py#L365-L370 to see what options you can provide to the tiler
