### ISSUE TITLE
Finding a tile zoom of 1 takes 30s when quadkey_zoom is at 10 (or higher)

### ISSUE THREAD

**Issue by bh-perennial** [developmentseed/cogeo-mosaic#236]
## Intro
👋 hi there....I'm a big fan of the library! When using it with my tile server I noticed that low zoom levels were taking a really long time and a big chunk of it was being spent in `find_quadkeys`. It's super helpful the function is cached, but I'd love to figure out how to get the function call down to be sub-second (as that is how it performs for higher zoom levels) . Equally I have some ideas of work-arounds that I wanted to discuss to make sure I wasn't doing everything completely wrong 😅 

## Reproduce the issue

Here is an example setup to reproduce the issue:

```python
from cogeo_mosaic.backends import MosaicBackend
import timeit

mosaic = MosaicBackend("https://raw.githubusercontent.com/developmentseed/mosaicjson-spec/refs/heads/master/0.0.3/example/dg_post_idai.json")

def run_mosaic_tile():
    try:
        mosaic.tile(1, 0, 1)
    except Exception:
        pass

print(f"Execution time: {timeit.timeit(run_mosaic_tile, number=1):.6f} seconds")
```

This prints `Execution time: 27.068926 seconds` for me.

The root of the issue makes sense as `find_quadkeys` will need to produce about 200k quad keys given the quadkey_zoom is at 10 and I'm asking for a zoom level of 1.

## Questions

So my specific questions are:
* Am I overlooking something or is this expected behavior?
* I acknowledge the min zoom is a really low level that I could just not allow users to get to? This could be an option to consider (I'm semi-new to the geo space) but if possible, I'd love to actually support this use case
* One workaround I've considered is to create multiple MosaicJSON files (at least one in the low zoom levels), for example one mosaic JSON at quadkey_zoom of 10  and another at a quadkey_zoom of 4 and route any zooms levels at 4 or lower to the quadkey_zoom of 4. Having multiple MosaicJSON files around feels a bit odd, but maybe I'm just incorrect to think that.

**Comment by vincentsarago** [comment]
Hi @bh-perennial 

> The root of the issue makes sense as find_quadkeys will need to produce about 200k quad keys given the quadkey_zoom is at 10 and I'm asking for a zoom level of 1.

😱 don't do that! this is just a level too far from the quadkey zoom level. Imagine you have 200k quadkey and each quad keys has 1 or 2 files, when trying to build a tile you'll try to open 200k-400k rasters (multiple times the same) 😱 

For a tile request to success I would say that you don't want to open more than 10 files!!! There is no magic with COG, it's not worth it to open a COG if it's to use for sub-pixel values 😅 

> I acknowledge the min zoom is a really low level that I could just not allow users to get to? This could be an option to consider (I'm semi-new to the geo space) but if possible, I'd love to actually support this use case

Just use a quadkey_zoom level which is in < than the min zoom of your data. https://github.com/developmentseed/mosaicjson-spec/tree/main/0.0.3#38-quadkey_zoom BUT still this should be couple levels up, not 9 levels. 

> One workaround I've considered is to create multiple MosaicJSON files (at least one in the low zoom levels), for example one mosaic JSON at quadkey_zoom of 10 and another at a quadkey_zoom of 4 and route any zooms levels at 4 or lower to the quadkey_zoom of 4. Having multiple MosaicJSON files around feels a bit odd, but maybe I'm just incorrect to think that.

Yeah we've looked into this a while ago https://github.com/developmentseed/mosaicjson-spec/discussions/22 but to be honest the `Static file model` should be deprecated. We know use `pgstac` for most of our mosaic backend https://github.com/stac-utils/titiler-pgstac but if you still want to have a simple static backend you might be better served with a geoparquet backend (https://github.com/developmentseed/cogeo-mosaic/issues/224)

**Comment by bh-perennial** [comment]
Thank you @vincentsarago for the super quick and really helpful response!
