### ISSUE TITLE
support pygeos

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/cogeo-mosaic#24]
I've found that [`pygeos`](https://github.com/pygeos/pygeos) can significantly speed up the creation of mosaicJSON by optimizing the [spatial operation to find assets which intersect each parent tile](https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/utils.py#L313-L325), especially when generating larger mosaics.

Pygeos should be [interoperable with shapely](https://github.com/pygeos/pygeos/blob/master/pygeos/io.py#L187-L223) on the next release (see https://github.com/Toblerity/Shapely/issues/782 for context), at which point I think it would make sense to add here.

**Comment by vincentsarago** [comment]
Thanks @geospatial-jeff, I'll have a look or if you want to open a PR I'll be happy to help

**Comment by geospatial-jeff** [comment]
I can do the PR, I'll start working on it this weekend!

**Comment by vincentsarago** [comment]
closed in #25 #26 thanks a lot @geospatial-jeff
