### ISSUE TITLE
publish to pip?

### ISSUE THREAD

**Issue by andrewharvey** [developmentseed/cogeo-mosaic#32]
```
> pip install cogeo-mosaic
Collecting cogeo-mosaic
  Could not find a version that satisfies the requirement cogeo-mosaic (from versions: )
No matching distribution found for cogeo-mosaic
```

**Comment by andrewharvey** [comment]
Oh `pip3 install cogeo-mosaic` install works. This is on Debian. Free free to close, but maybe an install note would help python newbies like myself.

**Comment by vincentsarago** [comment]
Hi @andrewharvey, yeah cogeo-mosaic support only python3, I'll add a note
Thanks
