### ISSUE TITLE
is order retained?

### ISSUE THREAD

**Issue by andrewharvey** [developmentseed/cogeo-mosaic#33]
the graphic at https://github.com/developmentseed/mosaicjson-spec/blob/master/Readme.md says something about the order of the tiles arrays, with newer images being at the start of the array.

Is it reasonable then to expect that the order of the files passed to `cogeo-mosaic create` is retained? And if so, would it be reasonable to document this in the README?

**Comment by vincentsarago** [comment]
Hey @andrewharvey thanks for the issue. 

> Is it reasonable then to expect that the order of the files passed to cogeo-mosaic create is retained?

Absolutely, and yes this is a good point to add in the readme 👍

**Comment by vincentsarago** [comment]
closed in https://github.com/developmentseed/cogeo-mosaic/commit/5f9782d58f40fcfea4b02b6f137a06a34efe785a
