### ISSUE TITLE
Refactor MosaicJSON parsing into base classes

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#37]

**Comment by vincentsarago** [comment]
Thanks for the issue @kylebarron. 

This came up after https://github.com/developmentseed/cogeo-mosaic-tiler/issues/3. 

Basically the idea is to add a DynamoDB Backend to store the mosaicJSON information (using quadkey as primary key. 

To enable DynamoDB we first need to refactor the way to load and read the mosaicJSON in https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/utils.py#L397-L488. 

To do:
- [ ] create ABC Base class
  Must have these methods
    - metadata
    - tile (find asset for a tile)
    - point (find asset for a coordinate)
    - create 
    - update
- [ ] add File Backend (no schema)
- [ ] add http Backend (http, https)
- [ ] add S3 Backend (s3://)
- [ ] add DynamoDB backend (dynamodb://? ) 

Will be great to write those class to be used like
```python
with DynamoDBBackedn(url) as mosaic:
     return mosaic.tile(qk)
```

We need to think how the new backend play with https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/utils.py#L397-L421 and how this will be transparent for the tiler! 

cc @kylebarron @geospatial-jeff

**Comment by kylebarron** [comment]
> Will be great to write those class to be used like
> 
> ```python
> with DynamoDBBackedn(url) as mosaic:
>      return mosaic.tile(qk)
> ```

I love it. I think that just means defining a couple context manager methods.

> We need to think how the new backend play with

I would think just call `BackendClass.tile()` instead of `fetch_and_find_assets`,  `BackendClass.point()` instead of `fetch_and_find_assets_point`, etc.

> how this will be transparent for the tiler

Somewhere just have a `switch`:
```py
backendClass
if scheme == 's3':
	BackendClass = S3Backend
elif scheme in ['http', 'https']:
	BackendClass = HttpBackend
elif scheme = 'dynamodb':
	BackendClass = DynamoDBBackend
else:
	BackendClass = FileBackend

with BackendClass(*args, **kwargs) as mosaic:
	mosaic.tile(x, y, z)
	mosaic.point(lng, lat)
```
?

**Comment by kylebarron** [comment]
https://github.com/developmentseed/cogeo-mosaic-tiler/blob/de15c97aa1f612a45c5200a0a13e8039d330a079/cogeo_mosaic_tiler/utils.py#L26-L51
This could also be refactored here
