### ISSUE TITLE
Use rtree when creating mosaic

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic#42]
Currently, the algorithm used when generating the mosaic is relatively slow: for every tile, it checks for intersection between that tile and _every asset bounds_. 
https://github.com/developmentseed/cogeo-mosaic/blob/bfe427c102129a8627750889d7b50341c2aa4c11/cogeo_mosaic/utils.py#L301-L304

I see you're using `pygeos` here, which is indeed faster than Shapely, but it still has to compute every pairwise intersection.

That can be made faster by using a tree.

Pygeos even includes a tree! https://pygeos.readthedocs.io/en/latest/strtree.html

And even cooler, it has a [`query_bulk`](https://pygeos.readthedocs.io/en/latest/strtree.html#pygeos.strtree.STRtree.query_bulk) method for vectorized querying of the tree! So you can pass all the tile geometries at once, and then have very few to double check intersections of.

cc @geospatial-jeff

**Comment by vincentsarago** [comment]
Go for it!

**Comment by kylebarron** [comment]
Good, because I'm writing up the PR now 😅

**Comment by vincentsarago** [comment]
done in #43 #58
