### ISSUE TITLE
Add STAC Backend ? 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic#80]
Questions:
- should we assume a STAC API + Query as input? 

```python
with STACBackend("https://jeffstacapi.hero", query=query, minzoom=4, maxzoom=12, quadkey=4) as mosaic:
```

On `init` the backend will `POST` to the api and construct the mosaic from the response 

Note: 
- This backend will be Read-Only (no write method)
- The POST request will be cached
- The List of asset will be composed of Item URLs

cc @geospatial-jeff

**Comment by geospatial-jeff** [comment]
> * should we assume a STAC API + Query as input?

I think this is probably the best way of doing it.  For larger requests, the backend would have to provide some way of dealing with pagination.  Maybe by paginating through the API until a certain number of items are read (`max_items=500`) or until the extent of the MosaicJSON is completely covered by at least one item.

It would be nice to support any STAC endpoint which returns a valid ItemCollection (both `/search` and `/collections/{collectionId}/items`).  The latter is less important but would let someone make a mosaicJSON for an entire collection which I can see use cases for.

> - The List of asset will be composed of Item URLs

My concern here is differentiating this from a MosaicJSON which references images directly. 
Maybe a mimetype key can be added to the MosaicJSON spec indicating the file type of the referenced files?   In the case of STAC, the mimetype would be set to `application/geo+json` to indicate that referenced files are an index.

**Comment by vincentsarago** [comment]
thanks @geospatial-jeff 

Here is a first sketch I did friday.

```python
"""cogeo-mosaic HTTP backend."""

import functools
import json
from typing import Any, Callable, Dict, List, Optional, Union

import mercantile
import requests

from cogeo_mosaic.backends.base import BaseBackend
from cogeo_mosaic.backends.utils import get_assets_from_json
from cogeo_mosaic.mosaic import MosaicJSON


def default_stac_accessor(feature: Dict):
    """Return specific feature identifier."""
    link = list(filter(lambda link: link["ref"] == "self", feature["links"]))[0]
    return link["href"]


class STACBackend(BaseBackend):
    """STAC Backend Adapter"""

    def __init__(
        self,
        url: str,
        minzoom: int,
        maxzoom: int,
        query: Dict = {},
        **kwargs: Any
    ):
        """Initialize HttpBackend."""
        self.path = url

        self.mosaic_def = self._read(json.dumps(query), minzoom, maxzoom, **kwargs)

    def tile(self, x: int, y: int, z: int) -> List[str]:
        """Retrieve assets for tile."""
        return get_assets_from_json(self.mosaic_def.tiles, self.quadkey_zoom, x, y, z)

    def point(self, lng: float, lat: float) -> List[str]:
        """Retrieve assets for point."""
        tile = mercantile.tile(lng, lat, self.quadkey_zoom)
        return get_assets_from_json(
            self.mosaic_def.tiles, self.quadkey_zoom, tile.x, tile.y, tile.z
        )

    def write(self):
        """Write mosaicjson document."""
        raise NotImplementedError

    def update(self, *args, **kwargs: Any):
        """Update the mosaicjson document."""
        raise NotImplementedError

    @functools.lru_cache(maxsize=512)
    def _read(  # type: ignore
        self,
        query: str,
        minzoom: int,
        maxzoom: int,
        accessor: Callable = default_stac_accessor,
        **kwargs: Any
    ) -> MosaicJSON:
        """Fetch STAC API and construct the mosaicjson."""
        headers = {
            "Content-Type": "application/json",
            "Accept-Encoding": "gzip",
            "Accept": "application/geo+json",
        }
        # TODO handle pagination
        data = requests.post(self.path, headers=headers, data=query).json()

        return MosaicJSON.from_features(
            data["features"],
            minzoom,
            maxzoom,
            accessor=accessor,
            **kwargs
        )

```


> It would be nice to support any STAC endpoint which returns a valid ItemCollection (both /search and /collections/{collectionId}/items).

I'm not sure to know what is a `valid itemCollection`


> Maybe by paginating through the API until a certain number of items are read (max_items=500) or until the extent of the MosaicJSON is completely covered by at least one item.

👌 max_items. 

>  until the extent of the MosaicJSON is completely covered by at least one item.

It might be a bit complex to handle but why not. 

> My concern here is differentiating this from a MosaicJSON which references images directly.
Maybe a mimetype key can be added to the MosaicJSON spec indicating the file type of the referenced files? In the case of STAC, the mimetype would be set to application/geo+json to indicate that referenced files are an index and requires additional logic to parse out the filename from the STAC item.

I like the idea, it would make also sense for mosaic based user input like landsat scene id.
