### ISSUE TITLE
LRU cache doesn't work on object method! 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic#83]
https://github.com/developmentseed/cogeo-mosaic/blob/7b6746a41ec8c5a2a9c618a9f9595ac3eccd85f9/cogeo_mosaic/backends/s3.py#L64

**Comment by kylebarron** [comment]
Why not?

**Comment by kylebarron** [comment]
https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-class-methods-release-object

**Comment by vincentsarago** [comment]
@kylebarron not sure I understand what you are meaning! 

I just tested locally and two consecutive call showed it wasn't cached 🤔

Also for S3, we might have a new client on each call so it won't be really cached and the `client` should be excluded from the `cache` parameters using https://cachetools.readthedocs.io/en/stable/
