### ISSUE TITLE
http backend supports ftp scheme but requests does not

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/cogeo-mosaic#87]
```python
with MosaicBackend("ftp://mosaic.json"):
    ...

>>> requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://mosaic.json'
```

Ref: https://stackoverflow.com/questions/11768214/python-download-a-file-from-an-ftp-server

**Comment by kylebarron** [comment]
oh sorry I just assumed

**Comment by geospatial-jeff** [comment]
It should probably be removed?  Don't think adding another backend for ftp is worth the time until a use case comes up.

**Comment by kylebarron** [comment]
Yes I agree, removing is probably simplest. Should also remove from the docs here:
https://github.com/developmentseed/cogeo-mosaic/blob/0b6824d3b05fd5014002ff74568c2194c0dc6adc/README.md#L169
